### ISSUE TITLE
Windows usage

### ISSUE THREAD

**Issue by Dequim** [hoperyy/vue-markdown-book#3]
Hello
I cant use it on windows. I tried with fresh node install too. It would be great to solve this problem. 
Thank you for your time!

`path.js:39
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'path', 'string');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:39:11)
    at Object.join (path.js:434:7)
    at Object.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\vue-markdown-book\gulpfile.js:12:26)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
child_process.js:615
    throw err;
    ^

Error: Command failed: node C:\Users\xxx\AppData\Roaming\npm\node_modules\vue-markdown-book\gulpfile.js task=dev cwd=C:\Users\xxx\Desktop\vue\eTicket
    at checkExecSyncError (child_process.js:575:11)
    at Object.execSync (child_process.js:612:13)
    at Command.commander.command.description.parse.action (C:\Users\xxx\AppData\Roaming\npm\node_modules\vue-markdown-book\bin\cmd.js:48:34)
    at Command.listener (C:\Users\xxx\AppData\Roaming\npm\node_modules\vue-markdown-book\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:180:13)
    at Command.parseArgs (C:\Users\xxx\AppData\Roaming\npm\node_modules\vue-markdown-book\node_modules\commander\index.js:651:12)
    at Command.parse (C:\Users\xxx\AppData\Roaming\npm\node_modules\vue-markdown-book\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\vue-markdown-book\bin\cmd.js:68:11)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
PS `C:\Users\xxx\Desktop\vue\eTicket>``

**Comment by hoperyy** [comment]
@Dequim 

Many Thanks for using it. Till now it only supports Mac OS. 

I'm thinking to make it support Windows too, but not very soon because I havn't a windows PC for testing for now.
